;
; Start of code
;
;            *= $7600
;

L5BC0:
	.repeat $100
	  .byte 0
	.endrep
L5CC0:
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
L5CE0:
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
L5D00:
	.repeat $100
	  .byte 0
	.endrep
L5E00:
            .byte $00,$00,$00,$00,$00,$00,$00,$02
            .byte $00,$00,$00,$00,$00,$00,$00,$BF
            .byte $00,$00,$00,$08,$0C,$18,$30,$67
            .byte $00,$00,$00,$00,$00,$00,$00,$F8
L5E20:
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$F0,$C2
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$00,$BF
            .byte $FF,$FF,$E7,$EB,$ED,$DB,$30,$67
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$03,$FB
L5E40:
	.repeat $100
	  .byte 0
	.endrep
L5F40:
            .byte $15,$2A,$20,$5F,$10,$52,$15,$50
            .byte $40,$AD,$00,$FF,$00,$AA,$7F,$00
            .byte $C0,$95,$00,$FF,$00,$AA,$FC,$00
            .byte $30,$60,$C0,$80,$80,$80,$80,$80
L5F60:
            .byte $95,$2A,$20,$5F,$10,$52,$15,$50
            .byte $40,$AD,$00,$FF,$00,$AA,$7F,$00
            .byte $C0,$95,$00,$FF,$00,$AA,$FC,$00
            .byte $33,$63,$C3,$83,$83,$83,$83,$83
L5F80:
	.repeat $100
	  .byte 0
	.endrep
L6080:
            .byte $17,$17,$10,$17,$13,$10,$1F,$00
            .byte $FF,$FF,$00,$FF,$FF,$00,$FF,$00
            .byte $FE,$FE,$00,$FE,$FC,$00,$FF,$00
            .byte $80,$80,$80,$80,$80,$80,$80,$00
L60A0:
            .byte $17,$97,$D0,$D7,$D3,$D0,$DF,$C0
            .byte $FF,$FF,$00,$FF,$FF,$00,$FF,$00
            .byte $FE,$FE,$00,$FE,$FC,$00,$FF,$00
L60B8:
            .byte $83,$83,$83,$83,$83,$87,$8F,$1F
L60C0:
L60E0 = L60C0+$20
	.repeat $100
	  .byte 0
	.endrep
L6180 = L61C0-$40
L61C0:
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
L61E0:
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
L6200:
	.repeat $100
	  .byte 0
	.endrep
L6300:
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$00
L6320:
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
L6340:
	.repeat $100
	  .byte 0
	.endrep
L6440:
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $00,$00,$00,$00,$00,$00,$00,$01
            .byte $00,$00,$00,$00,$00,$7F,$EA,$D5
            .byte $00,$00,$00,$00,$00,$C0,$E0,$70
L6460:
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FE,$FD
            .byte $FF,$FF,$FF,$FF,$80,$7F,$EA,$D5
            .byte $FF,$FF,$FF,$FF,$3F,$DF,$EF,$77
L6480:
	.repeat $100
	  .byte 0
	.endrep
L6580:
            .byte $00,$00,$00,$00,$00,$00,$00,$00
            .byte $01,$00,$07,$38,$7F,$40,$7F,$00
            .byte $AA,$01,$FC,$03,$E1,$18,$E0,$00
            .byte $B0,$50,$B0,$10,$C0,$78,$00,$00
L65A0:
            .byte $FF,$FF,$FF,$FF,$FF,$FF,$FF,$FF
            .byte $FD,$F8,$C7,$B8,$7F,$40,$7F,$80
            .byte $AA,$01,$FC,$03,$F1,$10,$E7,$0F
            .byte $B7,$57,$B7,$17,$C7,$7B,$87,$FF
